{
 "title": "Klipper Example",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(klipper_system_cpu, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Klipper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_system_cpu_temp{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "klipper_moonraker_cpu_usage{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "klipper_system_cpu{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "klipper_system_cpu_temp{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_system_memory_used{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Printer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Hotend",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_extruder_temperature{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Extruder",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "klipper_extruder_power{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "klipper_extruder_temperature{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "klipper_extruder_target{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "klipper_fan_speed{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Bed Heater",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_heater_bed_temperature{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heated Bed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "klipper_heater_bed_power{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "klipper_heater_bed_temperature{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "klipper_heater_bed_target{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(klipper_network_rx_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": " {{interface}} klipper_network_rx_bytes"
    },
    {
     "expr": "rate(klipper_network_tx_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{interface}} klipper_network_tx_bytes "
    }
   ]
  }
 ]
}