{
 "title": "Klipper Spoolman",
 "tags": [
  "klipper",
  "spoolman"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(klipper_spoolman_spool_info, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Spoolman Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Spoolman Connection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_spoolman_connected{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Spool",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_spoolman_active_spool_id{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Reports",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_spoolman_pending_reports{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Spools Tracked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(klipper_spoolman_spool_info{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Spool Inventory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Spool Inventory",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "klipper_spoolman_spool_info{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Spool {{spool_id}}"
    }
   ]
  },
  { "title": "Spool Weights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Remaining Weight",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "g" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_spoolman_remaining_weight{job=\"$job\", instance=\"$instance\"} * on(spool_id) group_right(filament_name, material, vendor) (klipper_spoolman_spool_info{job=\"$job\", instance=\"$instance\"} == 1)",
     "legendFormat": "{{vendor}} {{material}} {{filament_name}}"
    }
   ]
  },
  {
   "title": "Used Weight",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "g" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_spoolman_used_weight{job=\"$job\", instance=\"$instance\"} * on(spool_id) group_right(filament_name, material, vendor) (klipper_spoolman_spool_info{job=\"$job\", instance=\"$instance\"} == 1)",
     "legendFormat": "{{vendor}} {{material}} {{filament_name}}"
    }
   ]
  },
  {
   "title": "Spool Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(klipper_spoolman_used_weight{job=\"$job\", instance=\"$instance\"} / (klipper_spoolman_remaining_weight{job=\"$job\", instance=\"$instance\"} + klipper_spoolman_used_weight{job=\"$job\", instance=\"$instance\"}) * 100) * on(spool_id) group_right(filament_name, material, vendor) (klipper_spoolman_spool_info{job=\"$job\", instance=\"$instance\"} == 1)",
     "legendFormat": "{{vendor}} {{material}} {{filament_name}}"
    }
   ]
  },
  { "title": "Spool Lengths", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Remaining Length",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_spoolman_remaining_length{job=\"$job\", instance=\"$instance\"} * on(spool_id) group_right(filament_name, material, vendor) (klipper_spoolman_spool_info{job=\"$job\", instance=\"$instance\"} == 1)",
     "legendFormat": "{{vendor}} {{material}} {{filament_name}}"
    }
   ]
  },
  {
   "title": "Used Length",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_spoolman_used_length{job=\"$job\", instance=\"$instance\"} * on(spool_id) group_right(filament_name, material, vendor) (klipper_spoolman_spool_info{job=\"$job\", instance=\"$instance\"} == 1)",
     "legendFormat": "{{vendor}} {{material}} {{filament_name}}"
    }
   ]
  }
 ]
}